'use strict';
// ============================================================
//  Tiles & map props (16x16 metatiles, GBC 4-colour cells)
//  Ground tiles are opaque; object tiles may use '.' (clear).
// ============================================================
const TILES = {};     // name -> { rows | frames, solid, over, ... }
const TILE_IMG = {};  // name -> canvas (first frame) — for gallery
const TILE_FR = {};   // name -> [canvas, ...] animation frames
function tile(name, rows, opt = {}) { TILES[name] = Object.assign({ rows }, opt); }
// cut a big drawing into named 16x16 tiles: name_x_y
function bigTile(name, rows, opt = {}) {
  const h = rows.length / 16, w = rows[0].length / 16;
  const meta = { w, h, parts: [] };
  for (let ty = 0; ty < h; ty++) for (let tx = 0; tx < w; tx++) {
    const part = [];
    for (let y = 0; y < 16; y++) part.push(rows[ty * 16 + y].slice(tx * 16, tx * 16 + 16));
    const o = typeof opt === 'function' ? opt(tx, ty, w, h) : opt;
    tile(`${name}_${tx}_${ty}`, part, o);
    meta.parts.push(`${name}_${tx}_${ty}`);
  }
  BIG[name] = meta;
}
const BIG = {};

// ---------------- ground: snow town ----------------
tile('snow', [
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxWxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxwxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxWxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xwxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxWxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxwxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
], { soft: true });
tile('snow2', [
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxWWWWxxxxx',
  'xxxxxWWWWWWWWxxx',
  'xxxxwwwwwwwwwwxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xWxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxwxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
], { soft: true });
tile('snow3', [
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxGxxxxxxxxx',
  'xxxxxGxxGxxxxxxx',
  'xxxxxxGxGxxxxxxx',
  'xxxxWWWWWWxxxxxx',
  'xxxxxwwwwxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxWxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
], { soft: true });
// footprint-dotted snow near doors
tile('snow4', [
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxwwxxxxxxxxxxx',
  'xxxwwxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxwwxxxx',
  'xxxxxxxxxxwwxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxwwxxxxxxxxx',
  'xxxxxwwxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxwwxx',
  'xxxxxxxxxxxxwwxx',
  'xxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxx',
], { soft: true });
// 青石板 paving: pale staggered slabs, snow in the joints
tile('path', [
  'xxxxxxxxxxxgxxxx',
  'xwwwwwwwwwwgxwww',
  'xwwwwwwwwwwgxwww',
  'xwwwwwwwwwwgxwww',
  'xwwwwwwwwwwgxwwW',
  'xwwwwwwwwwwgxwww',
  'xwwwwwwwwwwgxwww',
  'ggggggggggggxwww',
  'xxxxxgxxxxxggggg',
  'xwwwwgxwwwwwwwww',
  'xwwwwgxwwwwwwwww',
  'xwWwwgxwwwwwwwww',
  'xwwwwgxwwwwwwwww',
  'xwwwwgxwwwwwwwww',
  'xwwwwgxwwwwwwwww',
  'gggggggggggggggg',
], { edge: 'snow' });
// packed dirt (forest, mountain)
tile('dirt', [
  'eeeeeeeeeeeeeeee',
  'eeeeeeeeeeeEeeee',
  'eeEeeeeeeeeeeeee',
  'eeeeeeeeeeeeeeee',
  'eeeeeeeezeeeeeee',
  'eeeeeEeeeeeeeeee',
  'eeeeeeeeeeeeeEee',
  'eeeeeeeeeeeeeeee',
  'ezeeeeeeeeeeeeee',
  'eeeeeeeeEeeeeeee',
  'eeeeeeeeeeeeeeee',
  'eeeeeeeeeeeezeee',
  'eeeEeeeeeeeeeeee',
  'eeeeeeeeeeeeeeee',
  'eeeeeeeeeEeeeeee',
  'eeeeeeeeeeeeeeee',
]);
// wooden bridge planks running left-right
tile('bridge', [
  'TTTTTTTTTTTTTTTT',
  'bbbbbbbbbbbbbbbb',
  'ttttTtttttttTttt',
  'ttttTtttttttTttt',
  'bbbbbbbbbbbbbbbb',
  'tttttttTtttttttT',
  'tttttttTtttttttT',
  'bbbbbbbbbbbbbbbb',
  'ttTtttttttTttttt',
  'ttTtttttttTttttt',
  'bbbbbbbbbbbbbbbb',
  'tttttTtttttttTtt',
  'tttttTtttttttTtt',
  'bbbbbbbbbbbbbbbb',
  'TTTTTTTTTTTTTTTT',
  'bbbbbbbbbbbbbbbb',
]);
tile('bridge_v', [
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbtttbTttbTtb',
  'bTttbTttbtttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbttb',
  'btttbTttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbtttbTtb',
  'bTttbtttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbTtb',
  'bTttbTttbTttbttb',
  'bTttbTttbTttbTtb',
]);
// river water (2 frames); edges are added by autotiling
tile('water', [
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BBBCCCBBBBBBBBBB',
  'BBBBBBCCBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBDDDBB',
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BDDDBBBBBBBBBBBB',
  'BBBBBBBBBCCCBBBB',
  'BBBBBBBBBBBBCCBB',
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BBBBBDDDBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
], { solid: true, water: true, anim: 'shift' });

// ---------------- town buildings (object layer) ----------------
// Roof row A: snow-capped ridge. Row B: dark tiles + eave with tile-ends.
tile('roofA_l', [
  '................',
  '..K.............',
  '..KK............',
  '..KUK...........',
  '...KUKKKKKKKKKKK',
  '...KUUUUUUUUUUUU',
  '..KWUwUUwUUwUUwU',
  '.KWWKKKKKKKKKKKK',
  '.KWWWWWWWWWWWWWW',
  'KWWWWWWWWWWWWWWW',
  'KWWwWWWwWWWwWWWw',
  'KWWwWWWwWWWwWWWw',
  'KWWwWWWwWWWwWWWw',
  'KWwwWWwwWWwwWWww',
  'KWUwWUwwWUwwWUww',
  'KWUwUUwUUUwUUUwU',
], { solid: true });
tile('roofA_m', [
  '................',
  '................',
  '................',
  '................',
  'KKKKKKKKKKKKKKKK',
  'UUUUUUUUUUUUUUUU',
  'UwUUwUUwUUwUUwUU',
  'KKKKKKKKKKKKKKKK',
  'WWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWW',
  'WWWwWWWwWWWwWWWw',
  'WWWwWWWwWWWwWWWw',
  'WWWwWWWwWWWwWWWw',
  'WWwwWWwwWWwwWWww',
  'WUwwWUwwWUwwWUww',
  'UUwUUUwUUUwUUUwU',
], { solid: true });
tile('roofB_l', [
  'KWUuUUuUUUuUUUuU',
  'KWUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KUUuUUuUUUuUUUuU',
  'KWWWWWWWWWWWWWWW',
  'KKKKKKKKKKKKKKKK',
  'KK.KUKKUKKUKKUKK',
  'K..KKKKKKKKKKKKK',
  '................',
  '................',
  '................',
], { solid: true });
tile('roofB_m', [
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'UUuUUUuUUUuUUUuU',
  'WWWWWWWWWWWWWWWW',
  'KKKKKKKKKKKKKKKK',
  'KUKKUKKUKKUKKUKK',
  'KKKKKKKKKKKKKKKK',
  '................',
  '................',
  '................',
], { solid: true });
// plaster wall, upper and lower courses (with eave shadow on top)
tile('wallU_l', [
  '..Kkkkkkkkkkkkkk',
  '..Kbbkkkkkkkkkkk',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTPPPPPPPPPPP',
], { solid: true });
tile('wallU_m', [
  'kkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkk',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true });
tile('wallD_l', [
  '..KbTbbbbbbbbbbb',
  '..KbTttttttttttt',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTppppppppppp',
  '..KbTPPPPPPPPPPP',
  '..Kbngnggnggnggn',
  '..Kbnnnnnnnnnnnn',
  '..Kbgnggnggnggng',
  '..KKnnnnnnnnnnnn',
  '..KKKKKKKKKKKKKK',
], { solid: true });
tile('wallD_m', [
  'bbbbbbbbbbbbbbbb',
  'tttttttttttttttt',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
  'ngnggnggnggnggng',
  'nnnnnnnnnnnnnnnn',
  'gnggnggnggnggngg',
  'nnnnnnnnnnnnnnnn',
  'KKKKKKKKKKKKKKKK',
], { solid: true });
// lattice window (warm paper — glows at night)
tile('window', [
  'kkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkk',
  'pppppppppppppppp',
  'ppbbbbbbbbbbbbpp',
  'ppbzzbzzbzzbzbpp',
  'ppbzzbzzbzzbzbpp',
  'ppbbbbbbbbbbbbpp',
  'ppbzzbzzbzzbzbpp',
  'ppbzzbzzbzzbzbpp',
  'ppbbbbbbbbbbbbpp',
  'ppbzzbzzbzzbzbpp',
  'ppbbbbbbbbbbbbpp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true, glow: true });
// round moon-window (for the inn)
tile('window_round', [
  'kkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkk',
  'pppppbbbbbbppppp',
  'pppbbzzbzzzbbppp',
  'ppbzzzzbzzzzzbpp',
  'ppbbbbbbbbbbbbpp',
  'pbzzzbzzzzbzzzbp',
  'pbzzzbzzzzbzzzbp',
  'pbbbbbbbbbbbbbbp',
  'ppbzzzzbzzzzzbpp',
  'ppbzzzzbzzzzzbpp',
  'pppbbzzbzzzbbppp',
  'pppppbbbbbbppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true, glow: true });
// double door, two tiles tall (top sits in the upper wall course)
tile('doorU', [
  'kkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkk',
  'ppKKKKKKKKKKKKpp',
  'ppKbbbbbbbbbbKpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRffRbRffRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRffRbRffRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRybyRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRffRbRffRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'PPKbRRRRbRRRRbPP',
], { solid: true });
tile('doorD', [
  'bbKbRRRRbRRRRbbb',
  'ttKbRRRRbRRRRbtt',
  'ppKbRffRbRffRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRffRbRffRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbRRRRbRRRRbpp',
  'ppKbbbbbbbbbbbpp',
  'PPKKKKKKKKKKKKPP',
  'ngnggggggggggggg',
  'nnnggggggggggnnn',
  'gnggwwwwwwwwggng',
  'nnnnnnnnnnnnnnnn',
  'KKKKKKKKKKKKKKKK',
], { door: true });
// open doorway variant (for shops) — dark interior
tile('doorD_open', [
  'bbKbbbbbbbbbbbbb',
  'ttKbKKKKKKKKKbtt',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'ppKbKkkkkkkkKbpp',
  'PPKbKkkkkkkkKbPP',
  'ngnKKkkkkkkkKKgg',
  'nnnggggggggggnnn',
  'gnggwwwwwwwwggng',
  'nnnnnnnnnnnnnnnn',
  'KKKKKKKKKKKKKKKK',
], { door: true });

// right-hand ends are mirrors of the left-hand pieces
for (const n of ['roofA', 'roofB', 'wallU', 'wallD']) {
  const L = TILES[n + '_l'];
  const o = Object.assign({}, L); delete o.rows;
  tile(n + '_r', flipRows(L.rows), o);
}

// ---------------- trees & plants ----------------
// 梅 — winter plum: crooked trunk, red-pink blossoms, snow along the boughs
bigTile('plum', [
  '................................',
  '...............mM...............',
  '.............mMmMm......mm......',
  '..............mbm......mMmm.....',
  '...mm..........b.....mm.mm......',
  '..mMMm.........bW...mMm.b.......',
  '...mmbWW......bWW....m..b...mm..',
  '.....bbbW.....b.......b..b.mMmm.',
  '.......bbW....b.....WWb...bbmm..',
  '..mm.....b...WbW....bb...b......',
  '.mMmm....bWW..b...bb...bb.......',
  '..mm.b....bbW.b..b....b.........',
  '......b.....bbb.b...bWWb...mm...',
  '.......b.....bbb...bbbb...mMmm..',
  '....mm.bWW....bb.bb.....bb.mm...',
  '...mMmm.bbW...bbbb....bb........',
  '....mm....bb..bbb..bbb..........',
  '............bbbbbbb.............',
  '.............TbbbW..............',
  '.............Tbbb...............',
  '............Tbbb................',
  '............Tbbb................',
  '............TTbbb...............',
  '.............Tbbb...............',
  '.............TTbbb..............',
  '..............Tbbb..............',
  '..............TTbbb.............',
  '.............TTbbbb.............',
  '............TTTbbbbb............',
  '...........wTTbbbbbbbw..........',
  '..........wwwwwwwwwwwww.........',
  '................................',
], (tx, ty) => ty === 0 ? { over: true } : { solid: true });
// snow pine, two tiles tall
bigTile('pine', [
  '.......WW.......',
  '......WWWv......',
  '......WWvv......',
  '.....WGGvvv.....',
  '.....WWWWvv.....',
  '....WGGGvvvv....',
  '...WWWGGvvvvv...',
  '...vWWWWWWvvv...',
  '..WGGGGGvvvvvv..',
  '..WWWGGGvvvvvv..',
  '.WWWWWWWWWWvvvv.',
  '.vGGGGGGGvvvvvv.',
  '.WWGGGGGGvvvvvvv',
  'WWWWWWGGGvvvvvvv',
  'vWWWWWWWWWWWvvvv',
  '.vvGGGGGGvvvvvv.',
  '..vvvvvvvvvvvv..',
  '....vvvbbvvv....',
  '.......bb.......',
  '.......bb.......',
  '......wbbw......',
  '.....wwwwww.....',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
], (tx, ty) => ty === 0 ? { over: true } : { solid: true });
// bare winter willow by the river
bigTile('willow', [
  '................................',
  '..........bbb...bb..............',
  '........bb...bbb..bbb...........',
  '......bb.W...Wb.....bb..........',
  '.....b..WWb..b.bW.....b.........',
  '....b...b..b.b..b......b........',
  '...b...b...bbb...b......b.......',
  '...b..b.....bb....b.....b.......',
  '..b...b.....bb.....b.....b......',
  '..b..b......bb.....b.....b......',
  '..b..b......bbW....b......b.....',
  '.b...b.....TbbW.....b.....b.....',
  '.b...b.....Tbb......b.....b.....',
  '.....b.....Tbb......b......b....',
  '.....b.....Tbbb.....b......b....',
  '.....b.....Tbbb.............b...',
  '...........Tbbb.................',
  '...........TTbb.................',
  '............Tbb.................',
  '............Tbbb................',
  '...........TTbbb................',
  '..........wTTbbbbw..............',
  '.........wwwwwwwwww.............',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
], (tx, ty) => ty === 0 ? { over: true } : { solid: tx === 0 });

// ---------------- props ----------------
tile('fence', [
  '................',
  '................',
  '..WW........WW..',
  '.KttK......KttK.',
  '.KtTK......KtTK.',
  'KKKKKKKKKKKKKKKK',
  'tttttttttttttttt',
  'TTTTTTTTTTTTTTTT',
  'KKKKKKKKKKKKKKKK',
  '.KtTK......KtTK.',
  '.KtTK......KtTK.',
  'KKKKKKKKKKKKKKKK',
  'tttttttttttttttt',
  'TTTTTTTTTTTTTTTT',
  'KKKKKKKKKKKKKKKK',
  '.wwww......wwww.',
], { solid: true });
tile('well', [
  '................',
  '...KKKKKKKKKK...',
  '..KbbbbbbbbbbK..',
  '..KTKKKKKKKKTK..',
  '..KT........TK..',
  '..KT........TK..',
  '.KWWWWWWWWWWWWK.',
  'KgggggggggggggnK',
  'KgKKKKKKKKKKKgnK',
  'KgKNNNNNNNNNKgnK',
  'KgKNNNCNNNNNKgnK',
  'KgnKKKKKKKKKngnK',
  'KgnggngnggnggnK.',
  'KnnnnnnnnnnnnnK.',
  '.KKKKKKKKKKKKKK.',
  '..wwwwwwwwwwww..',
], { solid: true });
tile('lantern_post', [
  '.......KK.......',
  '......KWWK......',
  '.....KKKKKK.....',
  '.....KrryrK.....',
  '.....KryyrK.....',
  '.....KrryrK.....',
  '.....KRrrRK.....',
  '......KKKK......',
  '.......Kb.......',
  '.......Kb.......',
  '.......Kb.......',
  '.......Kb.......',
  '.......Kb.......',
  '......KKbK......',
  '.....KbbbbK.....',
  '.....wwwwww.....',
], { solid: true, glow: true });
tile('stone_lantern', [
  '................',
  '.......KK.......',
  '.....KWWWWK.....',
  '....KWWWWWWK....',
  '....KKKKKKKK....',
  '.....KgggnK.....',
  '.....KoyogK.....',
  '.....KgggnK.....',
  '....KKKKKKKK....',
  '......KgnK......',
  '......KgnK......',
  '......KgnK......',
  '.....KggnnK.....',
  '....KggggnnK....',
  '....KKKKKKKK....',
  '...wwwwwwwwww...',
], { solid: true, glow: true });
tile('barrel', [
  '................',
  '................',
  '....KKKKKKKK....',
  '...KWWWWWWWWK...',
  '...KTWWWWWWTK...',
  '...KbTTTTTTbK...',
  '..KbtttttttTbK..',
  '..KKKKKKKKKKKK..',
  '..KbttttttttbK..',
  '..KbtttttttTbK..',
  '..KbtttttttTbK..',
  '..KKKKKKKKKKKK..',
  '...KbtttttTbK...',
  '...KKbbbbbbKK...',
  '....KKKKKKKK....',
  '...wwwwwwwwww...',
], { solid: true });
tile('crates', [
  '................',
  '.KKKKKKKK.......',
  '.KWWWWWWK.......',
  '.KttttttKKKKKKK.',
  '.KtKKKKtKWWWWWK.',
  '.KtKttKtKtttttK.',
  '.KtKKKKtKtKKKtK.',
  '.KttttttKtKtKtK.',
  '.KKKKKKKKtKKKtK.',
  '.KWWWWWWKtttttK.',
  '.KttttttKKKKKKK.',
  '.KtKKKKtKbbbbbK.',
  '.KtKttKtK.......',
  '.KtKKKKtK.......',
  '.KKKKKKKK.......',
  '.wwwwwwwwwwwww..',
], { solid: true });
tile('snowman', [
  '................',
  '.....KKKKKK.....',
  '....KbbbbbbK....',
  '...KKKKKKKKKK...',
  '....KWWWWWWK....',
  '...KWKWWWKWWK...',
  '...KWWWoWWWWK...',
  '...KWWWWWWWWK...',
  '....KrrrrrrrK...',
  '...KWWWrrWWWWK..',
  '..KWWWWWWKWWWWK.',
  '..KWWWWWWWWWWwK.',
  '..KWWWWWWKWWWwK.',
  '..KwWWWWWWWWwwK.',
  '...KKwwwwwwwKK..',
  '....wwwwwwwww...',
], { solid: true });
tile('sign', [
  '................',
  '................',
  '..KKKKKKKKKKKK..',
  '.KtttttttttttTK.',
  '.KtbbbbbbbbbbTK.',
  '.KttttttttttbTK.',
  '.KtbbbbbbbbttTK.',
  '.KtttttttttttTK.',
  '.KTTTTTTTTTTTTK.',
  '..KKKKKbbKKKKK..',
  '.......Kb.......',
  '.......Kb.......',
  '.......Kb.......',
  '......KKbK......',
  '......wwww......',
  '................',
], { solid: true });
tile('haystack', [
  '................',
  '................',
  '......WWWW......',
  '....WWWWWWWW....',
  '...KWWWzzWWWK...',
  '..KzzzzzzzzzaK..',
  '..KzzazzzazzaK..',
  '.KzzzzzazzzzzaK.',
  '.KzazzzzzzazzaK.',
  '.KzzzzazzzzzzaK.',
  '.KazzzzzzazzaaK.',
  '.KzzzazzzzzzaaK.',
  '..KaaaaaaaaaaK..',
  '...KKKKKKKKKK...',
  '..wwwwwwwwwwww..',
  '................',
], { solid: true });
tile('rock', [
  '................',
  '................',
  '................',
  '.....KKKKK......',
  '....KWWWWWK.....',
  '...KWWWWWWWKK...',
  '...KggWWWWWWWK..',
  '..KgggggggWWnK..',
  '..KggggggggnnK..',
  '..KgnggggggnnK..',
  '..KgggggggnnnK..',
  '...KnnnnnnnnK...',
  '....KKKKKKKK....',
  '...wwwwwwwwww...',
  '................',
  '................',
], { solid: true });
tile('stump', [
  '................',
  '................',
  '................',
  '................',
  '.....KKKKKK.....',
  '....KWWWWWWK....',
  '...KWWWWWWWWK...',
  '...KTtTTTTtTK...',
  '...KbTtttttbK...',
  '...KbTtTtttbK...',
  '...KbTtttTtbK...',
  '..KbbTttttttbK..',
  '..KKKKKKKKKKKK..',
  '..wwwwwwwwwwww..',
  '................',
  '................',
], { solid: true });
tile('bench', [
  '................',
  '................',
  '................',
  '................',
  '................',
  'KKKKKKKKKKKKKKKK',
  'WWWWWWWWWWWWWWWW',
  'tttttttttttttttt',
  'TTTTTTTTTTTTTTTT',
  'KKKKKKKKKKKKKKKK',
  '.KbK........KbK.',
  '.KbK........KbK.',
  '.KbK........KbK.',
  '.KKK........KKK.',
  '.www........www.',
  '................',
], { solid: true });
// notice board (告示)
tile('notice', [
  '................',
  'KKKKKKKKKKKKKKKK',
  'KUUUUUUUUUUUUUUK',
  'KKKKKKKKKKKKKKKK',
  '.KbKpppppppKbK..',
  '.KbKpKKpKKpKbK..',
  '.KbKpppppppKbK..',
  '.KbKpKpKKKpKbK..',
  '.KbKppppppPKbK..',
  '.KbKKKKKKKKKbK..',
  '.KbK.......KbK..',
  '.KbK.......KbK..',
  '.KbK.......KbK..',
  '.KKK.......KKK..',
  '.www.......www..',
  '................',
], { solid: true });
// red lantern hanging under eaves — drawn as a decal over the wall
tile('lantern_hang', [
  '.......K........',
  '.......K........',
  '......KKK.......',
  '.....KrrrK......',
  '....KrryrrK.....',
  '....KryyyrK.....',
  '....KrryrrK.....',
  '....KRrrrRK.....',
  '.....KKKKK......',
  '......K.K.......',
  '......y.y.......',
  '................',
  '................',
  '................',
  '................',
  '................',
], { decal: true, glow: true });

// ---------------- interiors ----------------
tile('floor_wood', [
  'ttttttttTttttttt',
  'ttttttttTttttttt',
  'ttttttttTttttttt',
  'bbbbbbbbbbbbbbbb',
  'ttttTttttttttttt',
  'ttttTttttttttttt',
  'ttttTttttttttttt',
  'bbbbbbbbbbbbbbbb',
  'tttttttttttTtttt',
  'tttttttttttTtttt',
  'tttttttttttTtttt',
  'bbbbbbbbbbbbbbbb',
  'ttTttttttttttttt',
  'ttTttttttttttttt',
  'ttTttttttttttttt',
  'bbbbbbbbbbbbbbbb',
]);
tile('floor_stone', [
  'gggggggngggggggn',
  'gwggggg ngggggggn'.slice(0, 16),
  'gggggggngggggggn',
  'gggggggngggggggn',
  'gggggggngggggggn',
  'gggggggngggggggn',
  'gggggggngggggggn',
  'nnnnnnnnnnnnnnnn',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'gggngggggggngggg',
  'nnnnnnnnnnnnnnnn',
]);
tile('floor_tatami', [
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zezzzzzzzzzzzzez',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zezzzzzzzzzzzzez',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zezzzzzzzzzzzzez',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzz',
  'zezzzzzzzzzzzzez',
  'EEEEEEEEEEEEEEEE',
]);
// back wall: plaster with wood rail; two rows tall
tile('iwall_top', [
  'bbbbbbbbbbbbbbbb',
  'TTTTTTTTTTTTTTTT',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true });
tile('iwall_bot', [
  'bbbbbbbbbbbbbbbb',
  'tttttttttttttttt',
  'TTTTTTTTTTTTTTTT',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'tTttttTttttttTtt',
  'TTTTTTTTTTTTTTTT',
  'bbbbbbbbbbbbbbbb',
  'KKKKKKKKKKKKKKKK',
  'kkkkkkkkkkkkkkkk',
], { solid: true });
tile('iwall_win', [
  'bbbbbbbbbbbbbbbb',
  'TTTTTTTTTTTTTTTT',
  'pppppppppppppppp',
  'ppbbbbbbbbbbbbpp',
  'ppbCCbcCbCCbCbpp',
  'ppbCcbCCbcCbCbpp',
  'ppbbbbbbbbbbbbpp',
  'ppbcCbCCbCcbCbpp',
  'ppbCCbCcbCCbcbpp',
  'ppbbbbbbbbbbbbpp',
  'ppbbbbbbbbbbbbpp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true });
// 山水 scroll painting
tile('iwall_scroll', [
  'bbbbbbbbbbbbbbbb',
  'TTTTTTTTTTTTTTTT',
  'pppppKKKKKKppppp',
  'ppppKbbbbbbKpppp',
  'pppppKWWWWKppppp',
  'pppppKWWWWKppppp',
  'pppppKWnWWKppppp',
  'pppppKnnWWKppppp',
  'pppppKWWnWKppppp',
  'pppppKWnnnKppppp',
  'pppppKnnWnKppppp',
  'pppppKWWWrKppppp',
  'ppppKbbbbbbKpppp',
  'pppppKKKKKKppppp',
  'pppppppppppppppp',
  'PPPPPPPPPPPPPPPP',
], { solid: true });
tile('exit', Array(16).fill('KKKKKKKKKKKKKKKK'));
tile('void', [
  'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK', 'KKKKKKKKKKKKKKKK',
], { solid: true });
tile('mat', [
  '................',
  '................',
  '................',
  '................',
  '..KKKKKKKKKKKK..',
  '..KrrrrrrrrrrK..',
  '..KrRRRRRRRRrK..',
  '..KrRyRRRRyRrK..',
  '..KrRRRRRRRRrK..',
  '..KrrrrrrrrrrK..',
  '..KKKKKKKKKKKK..',
  '................',
  '................',
  '................',
  '................',
  '................',
], { flat: true });
// table (2 wide)
bigTile('table', [
  '................................',
  '................................',
  '................................',
  '..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..',
  '.KttttttttttttttttttttttttttttK.',
  '.KtWtttttttttttttttttttttttttTK.',
  '.KttttttttttttttttttttttttttttK.',
  '.KtttttttttttttttttttttttttTTTK.',
  '.KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK.',
  '.KbbbbbbbbbbbbbbbbbbbbbbbbbbbbK.',
  '..KbK....................KbK....',
  '..KbK....................KbK....',
  '..KbK....................KbK....',
  '..KKK....................KKK....',
  '................................',
  '................................',
], { solid: true });
tile('stool', [
  '................',
  '................',
  '................',
  '................',
  '................',
  '.....KKKKKK.....',
  '....KttttttK....',
  '....KtttttTK....',
  '....KTTTTTTK....',
  '.....KbKKbK.....',
  '.....KbK.KbK....',
  '.....KKK.KKK....',
  '................',
  '................',
  '................',
  '................',
], { solid: true });
bigTile('bed', [
  '................',
  '.KKKKKKKKKKKKKK.',
  '.KbbbbbbbbbbbbK.',
  '.KbWWWWWWWWWWbK.',
  '.KbWWWWWWWWWWbK.',
  '.KbwwwwwwwwwwbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbBCBBBBBCBBbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbBBBBCBBBBBbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbBCBBBBBBCBbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbBBBBCBBBBBbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbDDDDDDDDDDbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbBCBBBBBCBBbK.',
  '.KbBBBBBBBBBBbK.',
  '.KbDDDDDDDDDDbK.',
  '.KbbbbbbbbbbbbK.',
  '.KKKKKKKKKKKKKK.',
  '.KbK........KbK.',
  '.KKK........KKK.',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
], { solid: true });
// shelf with jars against the back wall (2 tall)
bigTile('shelf', [
  'KKKKKKKKKKKKKKKK',
  'KbbbbbbbbbbbbbbK',
  'KbKKKbbKKKbKKKbK',
  'KbKmKbKCCKbKyKbK',
  'KbKKKbKCCKbKKKbK',
  'KbbbbbbbbbbbbbbK',
  'KTTTTTTTTTTTTTTK',
  'KbbbbbbbbbbbbbbK',
  'KbKKbbKKKbbKKKbK',
  'KbKrKbKGGKbKoKbK',
  'KbKKKbKGGKbKKKbK',
  'KbbbbbbbbbbbbbbK',
  'KTTTTTTTTTTTTTTK',
  'KbbbbbbbbbbbbbbK',
  'KbKKKKbbbKKKKKbK',
  'KbKttKbbbKttKbbK',
  'KbKKKKbbbKKKKbbK',
  'KbbbbbbbbbbbbbbK',
  'KTTTTTTTTTTTTTTK',
  'KbK..........KbK',
  'KKK..........KKK',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
], { solid: true });
// 药柜 — apothecary cabinet of tiny drawers (2 wide x 2 tall)
bigTile('herbcab', [
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbKtytKbKtytKbKtytKbKtytKbKtyKbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbKtytKbKtytKbKtytKbKtytKbKtyKbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbKtytKbKtytKbKtytKbKtytKbKtyKbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbKtytKbKtytKbKtytKbKtytKbKtyKbK',
  'KbKKKKKbKKKKKbKKKKKbKKKKKbKKKKbK',
  'KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK',
  'KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK',
  'KbK..........................KbK',
  'KKK..........................KKK',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
], { solid: true });
// shop counter (horizontal piece, tiles left/mid/right)
tile('counter_l', [
  '................',
  '................',
  '..KKKKKKKKKKKKKK',
  '.KttttttttttttttT',
  '.KtWttttttttttttt',
  '.KTTTTTTTTTTTTTTT',
  '.KbbbbbbbbbbbbbbbK'.slice(0, 16),
  '.KbtttbtttbtttbtK'.slice(0, 16),
  '.KbtttbtttbtttbtK'.slice(0, 16),
  '.KbtttbtttbtttbtK'.slice(0, 16),
  '.KbtttbtttbtttbtK'.slice(0, 16),
  '.KbbbbbbbbbbbbbbbK'.slice(0, 16),
  '.KKKKKKKKKKKKKKKK'.slice(0, 16),
  '................',
  '................',
  '................',
].map((r) => r.slice(0, 16)), { solid: true });
tile('counter_m', [
  '................',
  '................',
  'KKKKKKKKKKKKKKKK',
  'tttttttttttttttt',
  'tttttttttttttttt',
  'TTTTTTTTTTTTTTTT',
  'bbbbbbbbbbbbbbbb',
  'tttbtttbtttbtttb',
  'tttbtttbtttbtttb',
  'tttbtttbtttbtttb',
  'tttbtttbtttbtttb',
  'bbbbbbbbbbbbbbbb',
  'KKKKKKKKKKKKKKKK',
  '................',
  '................',
  '................',
], { solid: true });
tile('counter_r', [
  '................',
  '................',
  'KKKKKKKKKKKKKK..',
  'tttttttttttttTK.',
  'tttttttttttttTK.',
  'TTTTTTTTTTTTTTK.',
  'bbbbbbbbbbbbbbK.',
  'tttbtttbtttbtbK.',
  'tttbtttbtttbtbK.',
  'tttbtttbtttbtbK.',
  'tttbtttbtttbtbK.',
  'bbbbbbbbbbbbbbK.',
  'KKKKKKKKKKKKKK..',
  '................',
  '................',
  '................',
], { solid: true });
// forge furnace (2x2) with animated fire mouth
bigTile('furnace', [
  '......KKKKKKKKKKKKKKKKKKKK......',
  '......KnngnnngnngnnngnngnK......',
  '.....KKKKKKKKKKKKKKKKKKKKKK.....',
  '....KgggnggggnggggnggggngggK....',
  '...KgngggggnggggggnggggggnggK...',
  '...KgggnggKKKKKKKKKKKKggnggnK...',
  '...KggngKKRRRRRRRRRRRRKKgggnK...',
  '...KgggKRRooooooooooooRRKgnnK...',
  '...KgnKRooyyyyyyyyyyyyooRKgnK...',
  '...KggKRoyyOOOOOOOOOOyyyoRKnK...',
  '...KgnKRoyOOOOOOOOOOOOOyoRKnK...',
  '...KggKRoyyOOOOOOOOOOOyyoRKnK...',
  '...KgnKRooyyyyyyyyyyyyyooRKnK...',
  '...KggKKRRooooooooooooRRKKnnK...',
  '...KgnggKKKKKKKKKKKKKKKKgnnnK...',
  '...KggnggggnggggnggggnggggnnK...',
  '...KgngggnggggnggggnggggnnnnK...',
  '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
  '...KnnnnnnnnnnnnnnnnnnnnnnnnK...',
  '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
], { solid: true, glow: true });
tile('anvil', [
  '................',
  '................',
  '................',
  '................',
  '..KKKKKKKKKKK...',
  '.KnggggggggggK..',
  'KnggggggggggnK..',
  '.KKKnnnnnnnKK...',
  '....KnnnnnK.....',
  '....KknnnkK.....',
  '...KKkkkkkKK....',
  '..KbbbbbbbbbK...',
  '..KbTTTTTTTbK...',
  '..KKKKKKKKKKK...',
  '................',
  '................',
], { solid: true });
// weapon rack with swords (2 tall, against wall)
bigTile('rack', [
  'KKKKKKKKKKKKKKKK',
  'KbbbbbbbbbbbbbbK',
  'KbKWKbKWKbKWKbbK',
  'KbKwKbKwKbKwKbbK',
  'KbKwKbKwKbKwKbbK',
  'KbKwKbKwKbKwKbbK',
  'KbKwKbKwKbKwKbbK',
  'KbKwKbKwKbKwKbbK',
  'KbKwKbKwKbKwKbbK',
  'KKKKKKKKKKKKKKKK',
  'KyKKbKyKKbKyKbbK',
  'KbKRKbKbKKbKbKbK',
  'KbKRKbKbKbbKbKbK',
  'KbbbbbbbbbbbbbbK',
  'KTTTTTTTTTTTTTTK',
  'KbbbbbbbbbbbbbbK',
  'KbK..........KbK',
  'KKK..........KKK',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
], { solid: true });
tile('jar', [
  '................',
  '................',
  '................',
  '.....KKKKKK.....',
  '.....KbbbbK.....',
  '....KKKKKKKK....',
  '...KEEEEEEEEK...',
  '..KEzEEEEEEEhK..',
  '..KEzEEEEEEEhK..',
  '..KEEEEEEEEEhK..',
  '..KEEKKKKKKEhK..',
  '..KEEEEEEEEhhK..',
  '...KEEEEEEhhK...',
  '....KKKKKKKK....',
  '................',
  '................',
], { solid: true });
// 屏风 folding screen
tile('screen', [
  'KKKKKKKKKKKKKKKK',
  'KbbbbbKbbbbbKbbK',
  'KbWWWbKbWWWbKbWK',
  'KbWnWbKbWWWbKbWK',
  'KbnnWbKbWWnbKbWK',
  'KbWnWbKbWnnbKbnK',
  'KbWWWbKbWnWbKbnK',
  'KbWWWbKbWWWbKbWK',
  'KbWmWbKbWWWbKbWK',
  'KbmMmbKbWWWbKbWK',
  'KbWbWbKbWWWbKbWK',
  'KbbbbbKbbbbbKbbK',
  'KKKKKKKKKKKKKKKK',
  '.KbK...KbK...KbK',
  '.KKK...KKK...KKK',
  '................',
], { solid: true });
tile('stairs_down', [
  'KKKKKKKKKKKKKKKK',
  'KkkkkkkkkkkkkkkK',
  'KnnnnnnnnnnnnnnK',
  'KkkkkkkkkkkkkkkK',
  'KKKKKKKKKKKKKKKK',
  'KnnnnnnnnnnnnnnK',
  'KkkkkkkkkkkkkkkK',
  'KKKKKKKKKKKKKKKK',
  'KkkkkkkkkkkkkkkK',
  'KKKKKKKKKKKKKKKK',
  'KkkkkkkkkkkkkkkK',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
]);
tile('stairs_up', [
  'KKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKK',
  'KgggggggggggggnK',
  'KKKKKKKKKKKKKKKK',
  'KggggggggggggnnK',
  'KgggggggggggggnK',
  'KKKKKKKKKKKKKKKK',
  'KgggggggggggggnK',
  'KggggggggggggnnK',
  'KgggggggggggggnK',
  'KKKKKKKKKKKKKKKK',
  'KgggggggggggggnK',
  'KggggggggggggnnK',
  'KgggggggggggggnK',
  'KgggggggggggggnK',
  'KKKKKKKKKKKKKKKK',
]);
// treasure chest (closed / open)
tile('chest', [
  '................',
  '................',
  '................',
  '...KKKKKKKKKK...',
  '..KRRRRRRRRRRK..',
  '..KRrrrrrrrrRK..',
  '..KyyyyyyyyyyK..',
  '..KRRRRKKRRRRK..',
  '..KKKKKyyKKKKK..',
  '..KRRRRKKRRRRK..',
  '..KRrrrrrrrrRK..',
  '..KRrrrrrrrrRK..',
  '..KyyyyyyyyyyK..',
  '..KKKKKKKKKKKK..',
  '..wwwwwwwwwwww..',
  '................',
], { solid: true });
tile('chest_open', [
  '................',
  '...KKKKKKKKKK...',
  '..KRRRRRRRRRRK..',
  '..KyyyyyyyyyyK..',
  '..KKKKKKKKKKKK..',
  '..KkkkkkkkkkkK..',
  '..KkkkkkkkkkkK..',
  '..KRRRRRRRRRRK..',
  '..KKKKKKKKKKKK..',
  '..KRRRRKKRRRRK..',
  '..KRrrrrrrrrRK..',
  '..KRrrrrrrrrRK..',
  '..KyyyyyyyyyyK..',
  '..KKKKKKKKKKKK..',
  '..wwwwwwwwwwww..',
  '................',
], { solid: true });
// glowing save stone (灵石)
tile('savestone', [
  '................',
  '.......KK.......',
  '......KcCK......',
  '.....KcWCCK.....',
  '.....KcWCCK.....',
  '....KcWWCCBK....',
  '....KcWCCCBK....',
  '....KcCCCBBK....',
  '....KCCCCBBK....',
  '.....KCCBBK.....',
  '.....KKKKKK.....',
  '....KgggggnK....',
  '...KgggggggnK...',
  '...KnnnnnnnnK...',
  '...KKKKKKKKKK...',
  '..wwwwwwwwwwww..',
], { solid: true, glow: true });

// ---------------- soft edges where snow meets a path ----------------
// Built per side as transparent overlays; mask bits 1=N 2=E 4=S 8=W
const EDGE_SETS = {
  snow: { lip: 'x', hi: 'W', sh: 'g' },
  grass: { lip: 'l', hi: 'L', sh: 'E' },
  moss: { lip: 'G', hi: 'v', sh: 'h' },
};
function edgeSide(side, set) {
  const g = Array.from({ length: 16 }, () => Array(16).fill('.'));
  const rnd = mulberry(side * 97 + 13);
  for (let i = 0; i < 16; i++) {
    const depth = 2 + (rnd() < 0.45 ? 1 : 0) + (rnd() < 0.15 ? 1 : 0);
    for (let d = 0; d < depth; d++) {
      const c = d === 0 && rnd() < 0.3 ? set.hi : set.lip;
      put(i, d, c);
    }
    if (rnd() < 0.7) put(i, depth, set.sh);
  }
  function put(i, d, c) {
    if (side === 0) g[d][i] = c;            // north: rows from top
    else if (side === 2) g[15 - d][i] = d === 0 ? c : (c === set.sh ? set.sh : c); // south
    else if (side === 3) g[i][d] = c;       // west
    else g[i][15 - d] = c;                  // east
  }
  // south edge reads as the near bank: no shadow, just the lip
  if (side === 2) for (let y = 0; y < 16; y++) for (let x = 0; x < 16; x++) if (g[y][x] === set.sh) g[y][x] = '.';
  return art(g.map((r) => r.join('')));
}
const EDGE_IMG = {};
function edgeImgs(setName) {
  if (!EDGE_IMG[setName]) EDGE_IMG[setName] = [0, 1, 2, 3].map((s) => edgeSide(s, EDGE_SETS[setName]));
  return EDGE_IMG[setName];
}

// ---------------- autotiling for water ----------------
// mask bits: 1=N land, 2=E land, 4=S land, 8=W land
function waterVariant(rows, mask, landLip = 'x', lipShade = 'w', dark = 'D') {
  const g = rows.map((r) => r.split(''));
  if (mask & 1) { for (let x = 0; x < 16; x++) { g[0][x] = landLip; g[1][x] = lipShade; g[2][x] = dark; } }
  if (mask & 4) { for (let x = 0; x < 16; x++) { g[15][x] = dark; } }
  if (mask & 8) { for (let y = 0; y < 16; y++) { g[y][0] = landLip; g[y][1] = lipShade; if (g[y][2] !== landLip && g[y][2] !== lipShade) g[y][2] = dark; } }
  if (mask & 2) { for (let y = 0; y < 16; y++) { g[y][15] = landLip; g[y][14] = lipShade; if (g[y][13] !== landLip && g[y][13] !== lipShade) g[y][13] = dark; } }
  return g.map((r) => r.join(''));
}
function shiftRows(rows, dx) {
  return rows.map((r, y) => {
    const s = (dx * (y % 4 < 2 ? 1 : -1) + 16) % 16;
    return r.slice(16 - s) + r.slice(0, 16 - s);
  });
}

// Build every tile image (with animation frames)
function buildTiles() {
  for (const name in TILES) {
    const t = TILES[name];
    let frames;
    if (t.frames) frames = t.frames;
    else if (t.anim === 'shift') frames = [t.rows, shiftRows(t.rows, 2)];
    else frames = [t.rows];
    TILE_FR[name] = frames.map((r) => art(r));
    TILE_IMG[name] = TILE_FR[name][0];
  }
}
// Lazily build autotile variants of water-like tiles
const AUTO_CACHE = {};
function autoTile(base, mask) {
  const key = base + mask;
  if (AUTO_CACHE[key]) return AUTO_CACHE[key];
  const t = TILES[base];
  const lip = t.lip || ['x', 'w', 'D'];
  const f0 = waterVariant(t.rows, mask, ...lip);
  const frames = t.anim === 'shift' ? [f0, waterVariant(shiftRows(t.rows, 2), mask, ...lip)] : [f0];
  return (AUTO_CACHE[key] = frames.map((r) => art(r)));
}
