#!/usr/bin/env python3
"""Extract the glyphs the game actually uses from Fusion Pixel 12px (OFL-1.1)
and write js/font_data.js as a compact bitmap atlas.

Each glyph: 12 rows x 16 bits (big-endian), so 24 bytes, base64 for the lot.
"""
import base64, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BDF = os.path.join(ROOT, 'tools', 'fusion-pixel-12px-monospaced-zh_hans.bdf')
OUT = os.path.join(ROOT, 'js', 'font_data.js')

def load_bdf(path):
    glyphs = {}
    ascent = 10
    with open(path, encoding='utf-8') as f:
        lines = f.read().split('\n')
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith('FONT_ASCENT'):
            ascent = int(ln.split()[1])
        if ln.startswith('STARTCHAR'):
            enc = dw = None; bbx = None; rows = []
            i += 1
            while not lines[i].startswith('ENDCHAR'):
                p = lines[i].split()
                if p[0] == 'ENCODING': enc = int(p[1])
                elif p[0] == 'DWIDTH': dw = int(p[1])
                elif p[0] == 'BBX': bbx = tuple(int(v) for v in p[1:5])
                elif p[0] == 'BITMAP':
                    i += 1
                    while not lines[i].startswith('ENDCHAR'):
                        rows.append(lines[i].strip()); i += 1
                    break
                i += 1
            if enc is not None and enc >= 0:
                glyphs[enc] = (dw, bbx, rows)
        i += 1
    return glyphs, ascent

def cell(glyph, ascent):
    dw, (w, h, xo, yo), rows = glyph
    out = [0] * 12
    top = ascent - (yo + h)  # row in cell of the glyph's first bitmap row
    for r, hexrow in enumerate(rows):
        bits = int(hexrow, 16)
        nbits = len(hexrow) * 4
        y = top + r
        if not (0 <= y < 12): continue
        for c in range(w):
            if bits & (1 << (nbits - 1 - c)):
                x = xo + c
                if 0 <= x < 16:
                    out[y] |= 1 << (15 - x)
    return dw, out

def collect_chars():
    chars = set(chr(c) for c in range(32, 127))
    chars |= set('　，。！？：；、“”‘’…—（）《》「」『』·～【】')
    for path in glob.glob(os.path.join(ROOT, 'js', '*.js')):
        if path.endswith('font_data.js'): continue
        with open(path, encoding='utf-8') as f:
            txt = f.read()
        for ch in txt:
            if ord(ch) > 127: chars.add(ch)
    return sorted(chars, key=ord)

def main():
    glyphs, ascent = load_bdf(BDF)
    chars = collect_chars()
    data = bytearray(); widths = []; used = []; missing = []
    for ch in chars:
        g = glyphs.get(ord(ch))
        if g is None:
            missing.append(ch); continue
        dw, rows = cell(g, ascent)
        used.append(ch); widths.append(str(min(dw, 12)))
        for r in rows:
            data += bytes([(r >> 8) & 255, r & 255])
    js = ('// Generated by tools/build_font.py from Fusion Pixel Font 12px (SIL OFL 1.1)\n'
          '// https://github.com/TakWolf/fusion-pixel-font\n'
          'const FONT_DATA={chars:%s,widths:"%s",bits:"%s"};\n' % (
              _jsstr(''.join(used)),
              ''.join('c' if w == '12' else ('6' if w == '6' else w) for w in widths),
              base64.b64encode(bytes(data)).decode()))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(js)
    print('glyphs:', len(used), 'bytes:', len(data), 'missing:', ''.join(m for m in missing if ord(m) > 127))

def _jsstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

if __name__ == '__main__':
    main()
